export const profileActionTypes = {
  // Get Profile
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILE_LOADING: 'GET_PROFILE_LOADING',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',

  // Update Profile
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_LOADING: 'UPDATE_PROFILE_LOADING',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',

  // Add Address
  ADD_ADDRESS: 'ADD_ADDRESS',
  ADD_ADDRESS_LOADING: 'ADD_ADDRESS_LOADING',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_ERROR: 'ADD_ADDRESS_ERROR',

  // Update Address
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  UPDATE_ADDRESS_LOADING: 'UPDATE_ADDRESS_LOADING',
  UPDATE_ADDRESS_SUCCESS: 'UPDATE_ADDRESS_SUCCESS',
  UPDATE_ADDRESS_ERROR: 'UPDATE_ADDRESS_ERROR',

  // Delete Address
  DELETE_ADDRESS: 'DELETE_ADDRESS',
  DELETE_ADDRESS_LOADING: 'DELETE_ADDRESS_LOADING',
  DELETE_ADDRESS_SUCCESS: 'DELETE_ADDRESS_SUCCESS',
  DELETE_ADDRESS_ERROR: 'DELETE_ADDRESS_ERROR',
};