export const CartActionTypes = {
    // CREATE
CREATE_CART : "CREATE_CART",
CREATE_CART_SUCCESS : "CREATE_CART_SUCCESS",
CREATE_CART_LOADING : "CREATE_CART_LADING",
CREATE_CART_RESET : "CREATE_CART_LOADING",
CREATE_CART_ERROR : "CREATE_CART_ERROR",
// GET
GET_CART_DATA : "GET_CART_DATA",
GET_CART_DATA_SUCCESS : "GET_CART_DATA_SUCCESS",
GET_CART_DATA_LOADING : "GET_CART_DATA_LOADING",
GET_CART_DATA_RESET : "GET_CART_DATA_RESET",
GET_CART_DATA_ERROR : "GET_CART_DATA_ERROR",
// UPDATE
UPDATE_CART_DATA : "UPDATE_CART_DATA",
UPDATE_CART_DATA_SUCCESS : "UPDATE_CART_DATA_SUCCESS",
UPDATE_CART_DATA_LOADING : "UPDATE_CART_DATA_LOADING",
UPDATE_CART_DATA_RESET : "UPDATE_CART_DATA_RESET",
UPDATE_CART_DATA_ERROR : "UPDATE_CART_DATA_ERROR",
// DELETE
DELETE_CART_DATA : "DELETE_CART_DATA",
DELETE_CART_DATA_SUCCESS : "DELETE_CART_DATA_SUCCESS",
DELETE_CART_DATA_LOADING : "DELETE_CART_DATA_LOADING",
DELETE_CART_DATA_RESET : "DELETE_CART_DATA_RESET",
DELETE_CART_DATA_ERROR : "DELETE_CART_DATA_ERROR",

}

