export const chatActionTypes = {
  CHAT_SESSION_REQUEST: 'CHAT_SESSION_REQUEST',
  CHAT_SESSION_SUCCESS: 'CHAT_SESSION_SUCCESS',
  CHAT_SESSION_FAILURE: 'CHAT_SESSION_FAILURE',
  
  CHAT_HISTORY_REQUEST: 'CHAT_HISTORY_REQUEST',
  CHAT_HISTORY_SUCCESS: 'CHAT_HISTORY_SUCCESS',
  CHAT_HISTORY_FAILURE: 'CHAT_HISTORY_FAILURE',
  
  CHAT_SEND_MESSAGE: 'CHAT_SEND_MESSAGE',
  CHAT_RECEIVE_MESSAGE: 'CHAT_RECEIVE_MESSAGE',
  
  CHAT_CONNECT: 'CHAT_CONNECT',
  CHAT_DISCONNECT: 'CHAT_DISCONNECT',
  CHAT_CONNECTED: 'CHAT_CONNECTED',
  CHAT_DISCONNECTED: 'CHAT_DISCONNECTED',
  
  CHAT_TYPING_START: 'CHAT_TYPING_START',
  CHAT_TYPING_STOP: 'CHAT_TYPING_STOP',
  
  CHAT_VOICE_START: 'CHAT_VOICE_START',
  CHAT_VOICE_STOP: 'CHAT_VOICE_STOP',
  CHAT_VOICE_SEND: 'CHAT_VOICE_SEND',
  
  CHAT_RESET: 'CHAT_RESET'
};