export const reviewActionTypes = {
  // Get Reviews
  GET_REVIEWS: 'GET_REVIEWS',
  GET_REVIEWS_LOADING: 'GET_REVIEWS_LOADING',
  GET_REVIEWS_SUCCESS: 'GET_REVIEWS_SUCCESS',
  GET_REVIEWS_ERROR: 'GET_REVIEWS_ERROR',

  // Add Review
  ADD_REVIEW: 'ADD_REVIEW',
  ADD_REVIEW_LOADING: 'ADD_REVIEW_LOADING',
  ADD_REVIEW_SUCCESS: 'ADD_REVIEW_SUCCESS',
  ADD_REVIEW_ERROR: 'ADD_REVIEW_ERROR',
};