export const adminActionTypes = {
  // Dashboard
  GET_DASHBOARD_STATS: 'GET_DASHBOARD_STATS',
  GET_DASHBOARD_STATS_LOADING: 'GET_DASHBOARD_STATS_LOADING',
  GET_DASHBOARD_STATS_SUCCESS: 'GET_DASHBOARD_STATS_SUCCESS',
  GET_DASHBOARD_STATS_ERROR: 'GET_DASHBOARD_STATS_ERROR',
  
  // Users
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_USERS_LOADING: 'GET_ALL_USERS_LOADING',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
  
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
  UPDATE_USER_ROLE_LOADING: 'UPDATE_USER_ROLE_LOADING',
  UPDATE_USER_ROLE_SUCCESS: 'UPDATE_USER_ROLE_SUCCESS',
  UPDATE_USER_ROLE_ERROR: 'UPDATE_USER_ROLE_ERROR',
  
  // Products
  GET_ADMIN_PRODUCTS: 'GET_ADMIN_PRODUCTS',
  GET_ADMIN_PRODUCTS_LOADING: 'GET_ADMIN_PRODUCTS_LOADING',
  GET_ADMIN_PRODUCTS_SUCCESS: 'GET_ADMIN_PRODUCTS_SUCCESS',
  GET_ADMIN_PRODUCTS_ERROR: 'GET_ADMIN_PRODUCTS_ERROR',
  
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  CREATE_PRODUCT_LOADING: 'CREATE_PRODUCT_LOADING',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
  
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_LOADING: 'UPDATE_PRODUCT_LOADING',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
  
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCT_LOADING: 'DELETE_PRODUCT_LOADING',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',
  
  // Orders
  GET_ADMIN_ORDERS: 'GET_ADMIN_ORDERS',
  GET_ADMIN_ORDERS_LOADING: 'GET_ADMIN_ORDERS_LOADING',
  GET_ADMIN_ORDERS_SUCCESS: 'GET_ADMIN_ORDERS_SUCCESS',
  GET_ADMIN_ORDERS_ERROR: 'GET_ADMIN_ORDERS_ERROR',
  
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  UPDATE_ORDER_STATUS_LOADING: 'UPDATE_ORDER_STATUS_LOADING',
  UPDATE_ORDER_STATUS_SUCCESS: 'UPDATE_ORDER_STATUS_SUCCESS',
  UPDATE_ORDER_STATUS_ERROR: 'UPDATE_ORDER_STATUS_ERROR',
};