export const ProductActiontypes = {
    CREATE_PRODUCT : "CREATE_PRODUCT",
    CREATE_PRODUCT_SUCCESS : "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_LOADING : "CREATE_PRODUCT_LOADING",
    CREATE_PRODUCT_RESET : "CREATE_PRODUCT_RESET",
    CREATE_PRODUCT_ERROR : "CREATE_PRODUCT_ERROR",

    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_LOADING: "UPDATE_PRODUCT_LOADING",
    UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",
    UPDATE_PRODUCT_ERROR: "UPDATE_PRODUCT_ERROR",

    GET_PRODUCT : "GET_PRODUCT",
    GET_PRODUCT_SUCCESS : "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_LOADING : "GET_PRODUCT_LOADING",
    GET_PRODUCT_RESET : "GET_PRODUCT_RESET",
    GET_PRODUCT_ERROR : "GET_PRODUCT_ERROR",

    GET_PRODUCT_BY_ID : "GET_PRODUCT_BY_ID",
    GET_PRODUCT_BY_ID_SUCCESS : "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_LOADING : "GET_PRODUCT_BY_ID_LOADING",
    GET_PRODUCT_BY_ID_RESET : "GET_PRODUCT_BY_ID_RESET",
    GET_PRODUCT_BY_ID_ERROR : "GET_PRODUCT_BY_ID_ERROR",

}