export const authActionTypes = {
    // REGISTER
    AUTH_REGISTER: 'AUTH_REGISTER',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    AUTH_REGISTER_LOADING: 'AUTH_REGISTER_LOADING',
    AUTH_REGISTER_RESET: 'AUTH_REGISTER_RESET',
    AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
    // LOGIN
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_LOADING: 'AUTH_LOGIN_LOADING',
    AUTH_LOGIN_RESET: 'AUTH_LOGIN_RESET',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    // LOGOUT
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
    // USER PROFILE
    AUTH_GET_USER_PROFILE: 'AUTH_GET_USER_PROFILE',
    AUTH_GET_USER_PROFILE_SUCCESS: 'AUTH_GET_USER_PROFILE_SUCCESS',
    AUTH_GET_USER_PROFILE_FAILURE: 'AUTH_GET_USER_PROFILE_FAILURE',
    // UPDATE PROFILE
    AUTH_UPDATE_PROFILE: 'AUTH_UPDATE_PROFILE',
    AUTH_UPDATE_PROFILE_SUCCESS: 'AUTH_UPDATE_PROFILE_SUCCESS',
    AUTH_UPDATE_PROFILE_FAILURE: 'AUTH_UPDATE_PROFILE_FAILURE',
    // CHANGE PASSWORD
    AUTH_FORGOT_PASSWORD: 'AUTH_FORGOT_PASSWORD',
    AUTH_FORGOT_PASSWORD_SUCCESS: 'AUTH_FORGOT_PASSWORD_SUCCESS',
    AUTH_FORGOT_PASSWORD_FAILURE: 'AUTH_FORGOT_PASSWORD_FAILURE',
    
    AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
    AUTH_RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS',
    AUTH_RESET_PASSWORD_FAILURE: 'AUTH_RESET_PASSWORD_FAILURE',
    AUTH_VERIFY_EMAIL: 'AUTH_VERIFY_EMAIL',
    AUTH_VERIFY_EMAIL_SUCCESS: 'AUTH_VERIFY_EMAIL_SUCCESS',
    AUTH_VERIFY_EMAIL_FAILURE: 'AUTH_VERIFY_EMAIL_FAILURE',   
}