export const recommendationActionTypes = {
  // Get Related Products
  GET_RELATED_PRODUCTS: 'GET_RELATED_PRODUCTS',
  GET_RELATED_PRODUCTS_LOADING: 'GET_RELATED_PRODUCTS_LOADING',
  GET_RELATED_PRODUCTS_SUCCESS: 'GET_RELATED_PRODUCTS_SUCCESS',
  GET_RELATED_PRODUCTS_ERROR: 'GET_RELATED_PRODUCTS_ERROR',

  // Get Trending Products
  GET_TRENDING_PRODUCTS: 'GET_TRENDING_PRODUCTS',
  GET_TRENDING_PRODUCTS_LOADING: 'GET_TRENDING_PRODUCTS_LOADING',
  GET_TRENDING_PRODUCTS_SUCCESS: 'GET_TRENDING_PRODUCTS_SUCCESS',
  GET_TRENDING_PRODUCTS_ERROR: 'GET_TRENDING_PRODUCTS_ERROR',

  // Get Personalized Recommendations
  GET_PERSONALIZED_RECOMMENDATIONS: 'GET_PERSONALIZED_RECOMMENDATIONS',
  GET_PERSONALIZED_RECOMMENDATIONS_LOADING: 'GET_PERSONALIZED_RECOMMENDATIONS_LOADING',
  GET_PERSONALIZED_RECOMMENDATIONS_SUCCESS: 'GET_PERSONALIZED_RECOMMENDATIONS_SUCCESS',
  GET_PERSONALIZED_RECOMMENDATIONS_ERROR: 'GET_PERSONALIZED_RECOMMENDATIONS_ERROR',
};