export const orderActionTypes = {
  // Place Order
  PLACE_ORDER: 'PLACE_ORDER',
  PLACE_ORDER_LOADING: 'PLACE_ORDER_LOADING',
  PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
  PLACE_ORDER_ERROR: 'PLACE_ORDER_ERROR',

  // Get Order History
  GET_ORDER_HISTORY: 'GET_ORDER_HISTORY',
  GET_ORDER_HISTORY_LOADING: 'GET_ORDER_HISTORY_LOADING',
  GET_ORDER_HISTORY_SUCCESS: 'GET_ORDER_HISTORY_SUCCESS',
  GET_ORDER_HISTORY_ERROR: 'GET_ORDER_HISTORY_ERROR',

  // Get Order Details
  GET_ORDER_DETAILS: 'GET_ORDER_DETAILS',
  GET_ORDER_DETAILS_LOADING: 'GET_ORDER_DETAILS_LOADING',
  GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS',
  GET_ORDER_DETAILS_ERROR: 'GET_ORDER_DETAILS_ERROR',
};